#CReating Forntend ansible code:
- name: frontend configuration
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package: 
     name: nginx
     state: present
    
  - name: syart and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove rm -rf /usr/share/nginx/html/* file
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: carete html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download frontend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip
    
  - name: Extract frontend code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest:  /usr/share/nginx/html
      remote_src: yes

  - name: Copy expense conf content
    ansible.builtin.copy:
     src: expense.conf
     dest: /etc/nginx/default.d/expense.conf

  - name: Restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
     
