#Create Ec2 instances fro mysq, backend and frontend. create r53 records

- name: Create ec2 instances and r53 reocrds
  hosts: local
  connection: local
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: {{ item }}
      vpc_subnet_id: {{ subnet_id }}
      instance_type: t3.micro
      security_group: {{ sg_group_id }}
      image_id: {{ ami_id }}
    loop:
    - mysql
    - backend
    - frontend
    register: ec2_instances

  - name: print out of ec2_instances
    ansible.builtin.debug:
      msg: print output of instances is {{ ec2_instances }}
      
