#Craeting MySQL with Ansible

- name: Creating MySQL 
  hosts: mysql
  become: yes
  vars:
    root_pass: "ExpenseApp@1"
    zone_name: "mysql.telugudevops.online"
  tasks:
    - name: install mysql sever
      ansible.builtin.package:
        name: mysql-server
        state: present
    - name: Enable and start service mysqld
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Check MySQL root password 
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ root_pass }}"
        login_host: "{{ zone_name }}"
        ignore_errors: true
        register: mysql_info

    - name: print mysql_info
      ansible.builtin.debug:
        msg: print the output is {{ mysql_info }}


    - name: set root pasword to MySQL 
      ansible.builtin.command:  mysql_secure_installation --set-root-pass "{{ root_pass }}"
      when: mysql_info.failed is true
      