#Create Ec2 instances fro mysq, backend and frontend. create r53 records

- name: Create ec2 instances and r53 reocrds
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-0e2f888f786957beb"
    sg_group_id: "sg-09805cbd3e2c45d5b"
    ami_id: "ami-09c813fb71547fc4f"
    zone_name: "telugudevops.online"
  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: t3.micro
        security_group: "{{ sg_group_id }}"
        image_id: "{{ ami_id }}"
      loop:
      - mysql
      - backend
      - frontend
      register: ec2_instances

    - name: print out of ec2_instances
      ansible.builtin.debug:
        msg: print output of instances is {{ ec2_instances }}

  # - name: Create r53 reocrds
  #   amazon.aws.route53:
  #     state: present
  #     zone: {{ zone_name }}
  #     record: "{{ mysql}}. {{ zone_name }}"
  #     type: A
  #     ttl: 1
  #     value: "{{ private-ip }}"
  #     wait: true


